"""
Django settings for social_dashboard project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-szmfokrd%mj(c8^@r@ckckc&3&y)iloo-5d!)hn1htij&jcot2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'social_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <-- Here
                
                'social_django.context_processors.login_redirect', # <-- Here
            ],
        },
    },
]

WSGI_APPLICATION = 'social_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# Configuration for the Twitter API 

SOCIAL_AUTH_STATE_PARAMETER = True

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store session in DB securely
SESSION_SAVE_EVERY_REQUEST = True  # Save session state consistently


ADDITIONAL_APPS =[
    'social_django',
     'dashboard',
     'threads_dashboard',
     'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    
]
INSTALLED_APPS += ADDITIONAL_APPS

AUTHENTICATION_BACKENDS = (
     'social_core.backends.facebook.FacebookOAuth2',
    # 'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.github.GithubOAuth2',

    

    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

    # 'social_core.backends.twitter.TwitterOAuth',
    # 'django.contrib.auth.backends.ModelBackend',
)


FACEBOOK_APP_ID = "594912273068064"
FACEBOOK_APP_SECRET ="54bbad1afa8b61df4bf8d0bd67bed0e7"
FACEBOOK_REDIRECT_URI ="https://1fdd-205-254-169-164.ngrok-free.app/facebook/callback/"# set ur redirect uri
# FACEBOOK_ACCESS_TOKEN = "EAAIdEc61cCABO1zpLgrwzmaIlqZCddcyIdtuiZBVyZAwvLCDWZAhYlZBz4A98t2lLaxWkaiy0BKaw4h1yJqyMCVO8UvyYSOH6Ky0zQaFo2yHZCimDdPbuHFNwwAB2kOr2uL4fWsb66cOyBvvZA9NkOkl8JKv0Yz8DLtLyhJwJQgcQR9O5zpZAdjqmm7tddTjH8qjdkkjZAJZBF"





LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'






# Threads API settings
THREADS_APP_ID = '524652823879349'
THREADS_APP_SECRET = '14b7b1f60c7f04dbdb53cf9e0ebe4843'
THREADS_REDIRECT_URI = ' https://1fdd-205-254-169-164.ngrok-free.app/threads/callback/'# set ur redirect uri as set in the developer account


CSRF_TRUSTED_ORIGINS = [
    ' https://1fdd-205-254-169-164.ngrok-free.app',
]
